version: '3.7'

services:
  mongo:
    container_name: S22-mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: thisistherealadmin
      MONGO_INITDB_DATABASE: sgr
    volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

