name: PUSH TO AWS ECR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t s22-utec-pro-backend .
          docker tag s22-utec-pro-backend:latest public.ecr.aws/s5z8r0i9/s22-utec-pro-backend:latest
          docker push public.ecr.aws/s5z8r0i9/s22-utec-pro-backend:latest
      - name: Push to AWS ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: s22-utec-pro-backend:latest